<?php declare(strict_types=1);

namespace Le0daniel\PhpTsBindings\CodeGen\Utils;

use Le0daniel\PhpTsBindings\Typescript\Code\TypescriptFile;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

/**
 * What it means for a directory to hold a generated client: the files the generators named, and
 * nothing else. Both the artisan command and the code generation fixture ask the same class, so
 * writing and verifying can never disagree on the rules.
 */
final class OutputDirectory
{
    /**
     * @param array<string, TypescriptFile> $files Keys are paths relative to the directory.
     */
    public static function write(string $directory, array $files): void
    {
        // Everything generated is rewritten, so a module left over from an operation that no longer
        // exists would otherwise keep importing types that are gone.
        foreach (self::existingFileNames($directory) as $fileName) {
            unlink("{$directory}/{$fileName}");
        }

        if (!is_dir("{$directory}/lib")) {
            mkdir("{$directory}/lib", 0777, true);
        }

        foreach ($files as $fileName => $file) {
            file_put_contents("{$directory}/{$fileName}", $file->toString());
        }
    }

    /**
     * The check the writer makes unnecessary, without touching the directory: every named file
     * exists with exactly the generated bytes, and no other TypeScript file is present.
     *
     * @param array<string, TypescriptFile> $files Keys are paths relative to the directory.
     * @return list<string> Empty when the directory matches. One human readable issue per problem.
     */
    public static function verify(string $directory, array $files): array
    {
        $issues = [];

        foreach ($files as $fileName => $file) {
            $filePath = "{$directory}/{$fileName}";
            if (!file_exists($filePath)) {
                $issues[] = "File {$fileName} is missing.";
                continue;
            }

            if (file_get_contents($filePath) !== $file->toString()) {
                $issues[] = "File {$fileName} does not match the generated output.";
            }
        }

        // A removed operation leaves its module behind. Comparing content alone reports that
        // directory as correct, which is exactly the drift this is meant to catch.
        foreach (self::existingFileNames($directory) as $fileName) {
            if (!array_key_exists($fileName, $files)) {
                $issues[] = "File {$fileName} is not generated anymore and should be deleted.";
            }
        }

        sort($issues);
        return $issues;
    }

    /**
     * Relative, not absolute: the caller's directory may be a relative or symlinked path, and only
     * the part below it can be compared to what the generators named.
     *
     * @return list<string> Every .ts file below the directory, relative to it.
     */
    private static function existingFileNames(string $directory): array
    {
        $root = realpath($directory);
        if ($root === false) {
            return [];
        }

        $fileNames = [];
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($root, RecursiveDirectoryIterator::SKIP_DOTS)
        );

        /** @var SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->isDir() || !str_ends_with($file->getBasename(), '.ts')) {
                continue;
            }

            $realPath = $file->getRealPath();
            if ($realPath === false) {
                continue;
            }

            $fileNames[] = substr($realPath, strlen($root) + 1);
        }

        sort($fileNames);
        return $fileNames;
    }
}
