<?php

declare(strict_types=1);

namespace Le0daniel\PhpTsBindings\CodeGen\Utils;

use Le0daniel\PhpTsBindings\CodeGen\Exceptions\CodeGenException;
use Le0daniel\PhpTsBindings\Typescript\Code\TypescriptFile;
use Le0daniel\PhpTsBindings\Utils\Assertions;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

/**
 * What it means for a directory to hold a generated client: the files the generators named, and
 * nothing else. Both the artisan command and the code generation fixture ask the same class, so
 * writing and verifying can never disagree on the rules.
 */
final class OutputDirectory
{
    public static function clear(string $directory): void
    {
        foreach (self::existingFileNames($directory) as $fileName) {
            "{$directory}/{$fileName}"
                |> realpath(...)
                |> Assertions::string(...)
                |> unlink(...)
                |> Assertions::true(...);
        }
    }

    /**
     * @param array<string, TypescriptFile> $files Keys are paths relative to the directory.
     */
    public static function write(string $directory, array $files): void
    {
        // Everything generated is rewritten, so a module left over from an operation that no longer
        // exists would otherwise keep importing types that are gone. Only files carrying the marker
        // are removed - the directory may legitimately hold TypeScript nobody here wrote.
        self::clear($directory);

        // A file about to be written that is already there unmarked is hand written TypeScript
        // whose name collides with a generated module. Overwriting it silently is the one case
        // the marker cannot recover from, so it is refused before anything is touched.
        foreach ($files as $fileName => $file) {
            $filePath = "{$directory}/{$fileName}";
            if (file_exists($filePath)) {
                throw new CodeGenException(
                    "Refusing to overwrite {$fileName}: it exists but does not carry the "
                    . "'" . TypescriptFile::MARKER . "' marker, so it was not written by this "
                    . 'library. Either it is hand written and the output belongs somewhere else, '
                    . 'or it predates the marker - delete the output directory once and generate '
                    . 'again.'
                );
            }
        }

        foreach ($files as $fileName => $file) {
            $fullPath = "{$directory}/{$fileName}";
            $directoryPath = dirname($fullPath);

            if (!file_exists($directoryPath) && !is_dir($directoryPath)) {
                mkdir($directoryPath, 0777, true);
            }

            file_put_contents($fullPath, $file->toString());
        }
    }

    /**
     * The check the writer makes unnecessary, without touching the directory: every named file
     * exists with exactly the generated bytes, and no other TypeScript file is present.
     *
     * @param array<string, TypescriptFile> $files Keys are paths relative to the directory.
     * @return list<string> Empty when the directory matches. One human readable issue per problem.
     */
    public static function verify(string $directory, array $files): array
    {
        $issues = [];

        foreach ($files as $fileName => $file) {
            $filePath = "{$directory}/{$fileName}";
            if (!file_exists($filePath)) {
                $issues[] = "File {$fileName} is missing.";

                continue;
            }

            if (file_get_contents($filePath) !== $file->toString()) {
                $issues[] = "File {$fileName} does not match the generated output.";
            }
        }

        // A removed operation leaves its module behind. Comparing content alone reports that
        // directory as correct, which is exactly the drift this is meant to catch.
        foreach (self::existingFileNames($directory) as $fileName) {
            if (!array_key_exists($fileName, $files)) {
                $issues[] = "File {$fileName} is not generated anymore and should be deleted.";
            }
        }

        sort($issues);

        return $issues;
    }

    /**
     * Relative, not absolute: the caller's directory may be a relative or symlinked path, and only
     * the part below it can be compared to what the generators named.
     *
     * Only files this library wrote are reported. That is what makes write() safe to run against a
     * directory holding anything else, and it keeps verify() from calling a hand written module
     * stale.
     *
     * @return list<string> Every generated .ts file below the directory, relative to it.
     */
    private static function existingFileNames(string $directory): array
    {
        $root = realpath($directory);
        if ($root === false) {
            return [];
        }

        $fileNames = [];
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($root, RecursiveDirectoryIterator::SKIP_DOTS)
        );

        /** @var SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->isDir() || !str_ends_with($file->getBasename(), '.ts')) {
                continue;
            }

            $realPath = $file->getRealPath();
            if ($realPath === false || !self::isGeneratedFile($realPath)) {
                continue;
            }

            $fileNames[] = substr($realPath, strlen($root) + 1);
        }

        sort($fileNames);

        return $fileNames;
    }

    /**
     * Reads only as much of the file as the marker needs.
     */
    private static function isGeneratedFile(string $filePath): bool
    {
        $head = file_get_contents($filePath, length: strlen(TypescriptFile::MARKER) + 2);

        return $head !== false && TypescriptFile::isGenerated($head);
    }
}
